export enum TeamStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum TeamRole {
  LEADER = 'LEADER',
  MEMBER = 'MEMBER',
  GUEST = 'GUEST',
  COORDINATOR = 'COORDINATOR',
  ADVISOR = 'ADVISOR',
  REVIEWER = 'REVIEWER',
  SUPPORT = 'SUPPORT',
  COMMUNICATOR = 'COMMUNICATOR',
}
